[2023-07-24T11:16:32.191+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: send_email_to_user.send_email manual__2023-07-24T11:11:30.493070+00:00 [queued]>
[2023-07-24T11:16:32.203+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: send_email_to_user.send_email manual__2023-07-24T11:11:30.493070+00:00 [queued]>
[2023-07-24T11:16:32.204+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-24T11:16:32.206+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-07-24T11:16:32.207+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-24T11:16:32.224+0000] {taskinstance.py:1304} INFO - Executing <Task(EmailOperator): send_email> on 2023-07-24 11:11:30.493070+00:00
[2023-07-24T11:16:32.232+0000] {standard_task_runner.py:55} INFO - Started process 5677 to run task
[2023-07-24T11:16:32.237+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'send_email_to_user', 'send_email', 'manual__2023-07-24T11:11:30.493070+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmp2wc4iph3']
[2023-07-24T11:16:32.240+0000] {standard_task_runner.py:83} INFO - Job 59: Subtask send_email
[2023-07-24T11:16:32.326+0000] {task_command.py:389} INFO - Running <TaskInstance: send_email_to_user.send_email manual__2023-07-24T11:11:30.493070+00:00 [running]> on host 907bbb26ec4d
[2023-07-24T11:16:32.415+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_email_to_user
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2023-07-24T11:11:30.493070+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-24T11:11:30.493070+00:00
[2023-07-24T11:16:32.437+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:120 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-07-24T11:16:32.438+0000] {configuration.py:635} WARNING - section/key [smtp/smtp_user] not found in config
[2023-07-24T11:16:32.440+0000] {email.py:229} INFO - Email alerting: attempt 1
[2023-07-24T11:16:32.441+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-07-24T11:16:32.452+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=send_email_to_user, task_id=send_email, execution_date=20230724T111130, start_date=20230724T111632, end_date=20230724T111632
[2023-07-24T11:16:32.466+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 59 for task send_email ([Errno 99] Cannot assign requested address; 5677)
[2023-07-24T11:16:32.490+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-24T11:16:32.514+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
